### ISSUE TITLE
change the style

### ISSUE THREAD

**Issue by parisash** [A-Kasaaian/react-advance-jalaali-datepicker#10]
would you please tell me how to add my custom style? 
I import my style.js, but it will not work.

Thanks so much

**Comment by A-Kasaaian** [comment]
If you follow read me construction, you may find `customClass`. Add customClass to the component and style it as you wish in your style sheet. No need to add style.js.
That file is the default style.

**Comment by A-Kasaaian** [comment]
@parisash sorry for late answer. You are doing right. It will add class to parent element then you may style child elements as you wish. If you are using range picker, please read the related part in readme doc.
