### ISSUE TITLE
DateTimeRangePicker preSelected

### ISSUE THREAD

**Issue by mozhdehhmd** [A-Kasaaian/react-advance-jalaali-datepicker#12]
hi I want to have preSelected values for DateTimeRangePicker how should I use it?
 and also want to choose date by clicking on it not on accept button also close picker by clicking on any where not only cancel cancel button
thanks

**Comment by A-Kasaaian** [comment]
Excuse me for late answer.
What you asked are not available by now. but they are simple changes. I'll consider them for the next release. I'll release next version asap.

**Comment by A-Kasaaian** [comment]
@mozhdehhmd I'm working on a new release. I read your requests.
first of all, DatePicker and DateRangePicker both submit on the date click. But, it is not a good Idea to submit DateTimePicker on the date click as time should be selected and is required.

preSelected value for start date and date time in range pickers will be added.

Cancel on background click will also be available.

**Comment by A-Kasaaian** [comment]
New version 1.1.0 is released and all the promised features are included
