### ISSUE TITLE
i need to set today date  in datepicker or today in preselect ?

### ISSUE THREAD

**Issue by riazi** [A-Kasaaian/react-advance-jalaali-datepicker#24]
hi
i need in datepicker show today in different style and in pre-select use today 
tnx for component

**Comment by A-Kasaaian** [comment]
I will update the README, but meanwhile you can use `current-date` class to style today. in the calendar you can find today has additional class of `current-date` .

But inOrder to set today as preselected, it depends on your date system. You should pass the date as preSelected and the format props. This Library is not in charge of your date selection. As I added controlling values from user component, preSelected can not be set statically inside the library.

**Comment by riazi** [comment]
> current-date

tnx
