### ISSUE TITLE
type a date

### ISSUE THREAD

**Issue by mghafariha** [A-Kasaaian/react-advance-jalaali-datepicker#25]
i want to have a option that user can types their date in datepickers. how can i change that?

**Comment by A-Kasaaian** [comment]
That's not supported now.
My proposal is using an input to type and onchange of that you update the value of your date picker. You also can style the component like a button.

**Comment by mghafariha** [comment]
Thank for your answering.

**Comment by A-Kasaaian** [comment]
No problem. This component is a date picker the rest should be handled by you, but in case you needed help, Open an issue or ask on stackoverflow.

**Comment by mghafariha** [comment]
Thanks, I try to solve it, i made attempt to create my datepicker but i stuck in handling on changevalue,unfortunetly,i dont have time now so i search for easy solution.your work is very helpful.thanks
