### ISSUE TITLE
Input can not be cleared!

### ISSUE THREAD

**Issue by atarazavi** [A-Kasaaian/react-advance-jalaali-datepicker#27]
Hi, Thanks for your useful component
The problem that I've faced into, is that it's impossible to clear the chosen date from the input! also Backspace and Delete buttons f keyboard not working!
I'm using it on a filtering page, so I need it to be cleared if client want to.
I also tried to add an external button which change the state and change the this.state.ChosenDate to an empty string, but I cannot change the input value grammatically! even with preSelected={this.state.ChosenDate} and controllValue={true}

**Comment by A-Kasaaian** [comment]
What is the version you are using?
Make sure you are using latest version. Follow the example (here)<https://github.com/A-Kasaaian/react-advance-jalaali-datepicker/blob/master/examples/controlValue.js>

**Comment by A-Kasaaian** [comment]
Follow the same reported issue which is resolved, https://github.com/A-Kasaaian/react-advance-jalaali-datepicker/issues/16

**Comment by A-Kasaaian** [comment]
I close this issue. If there was any further questions reopen this issue.
