### ISSUE TITLE
آپدیت

### ISSUE THREAD

**Issue by mahshid22** [A-Kasaaian/react-advance-jalaali-datepicker#28]
سلام من ماژول شمارو نصب کردم قبلا و الان میخوام آپدیتش کنم تا از امکاناتی مثل cancelOnBackgroundClick استفاده کنم
اما با دستور 
npm i react-advance-jalaali-datepicker
آپدیت نمیشه و پکیچ را هم که دانلود میکنم و بجای قبلی کپی میکنم بعد از استارت مجدد با ارور
Invalid Jalaali year -100721
مواجه میشم.
لطفا به بنده کمک کنید
سپاس

**Comment by A-Kasaaian** [comment]
Please take a look at this tutorial: https://60devs.com/npm-install-specific-version.html
`npm i react-advance-jalaali-datepicker@1.2.2`
