### ISSUE TITLE
Cant change minute when i don't wanna change hour

### ISSUE THREAD

**Issue by mrlaseptima** [A-Kasaaian/react-advance-jalaali-datepicker#29]
hi .thanks for this package
i have a problem with DateTimePicker . 
when i want change just minute i cant change that because i must change hour first and then change minutes . but sometimes that default hour is exactly that hour i want so i should change hour to another time then change that hour again to previous hour and then change minutes .
please fix this bug . thank you

**Comment by A-Kasaaian** [comment]
OK, good catch. It'll be resolved in the next release.

**Comment by A-Kasaaian** [comment]
Resolved in V1.3.1
