### ISSUE TITLE
types for typescript?

### ISSUE THREAD

**Issue by penkong** [A-Kasaaian/react-advance-jalaali-datepicker#31]
seems there is not any types for this package , is there any future plan to add this : 
@types/react-advance-jalaali-datepicker ?????

**Comment by ali-smartbear** [comment]
Sorry for the late answer. It was due to holiday :) 
No, unfortunately I do not have enough time for that. I'll appreciate if anyone helps me :)

**Comment by A-Kasaaian** [comment]
Type script added.
