### ISSUE TITLE
moment.weekday return invalid number

### ISSUE THREAD

**Issue by smkhadishi** [A-Kasaaian/react-advance-jalaali-datepicker#32]
selectedMonthFirstDay: moment(
        moment().format("jYYYY") + "/" + moment().format("jMM") + "/01",
        "jYYYY/jMM/jDD"
).weekday()
notice:
moment("1398/10/01", "jYYYY/jMM/jDD").weekday() return 1 with loadPersian and return 0 without loadPersion but must be 2

**Comment by A-Kasaaian** [comment]
Sorry but it's momentjs question. Ask your question on stackoverflow or https://github.com/jalaali/moment-jalaali.
