### ISSUE TITLE
How I can remove date from input 

### ISSUE THREAD

**Issue by fatemehalimardaani** [A-Kasaaian/react-advance-jalaali-datepicker#39]
I used this packege in my projects but I have a problem I cant find how user can delete date not edit only delete.

**Comment by A-Kasaaian** [comment]
You can simply use custom input feature, or control from outside which allows you to handle the value from the parent component

**Comment by fatemehalimardaani** [comment]
No, this is not about control from the parent component. I want when we enter the date , then we can delete it. Now I do everything. Only the date can be edited.
You can no longer empty the input

**Comment by fatemehalimardaani** [comment]
I do not want to delete the Input. Simply I want to empty the Input.
Like text input, we can delete the value of the input and turn it into placeholder text.

**Comment by A-Kasaaian** [comment]
If you are handling the value in the state of your component just clear the state. Deleting the was an issue but it got resolved while ago #16 
There are solutions but it depends on your component architecture

**Comment by A-Kasaaian** [comment]
@fatemehalimardaani paste here the your component code or the part you used this library

**Comment by fatemehalimardaani** [comment]
سلام خوبید ؟‌من از پکیجتون استفاده کردم ی مشکلی باهاش دارم میتونم ID
TELEGRAM تونو داشته باشم اونجا باهم صحبت کنیم؟

**Comment by A-Kasaaian** [comment]
As I've haven't heard you for so long, I close this discussion. Please, don't hesitate to open it again.

**Comment by masarbazi** [comment]
I think this issue should be reopened. 
I know there is ```inputComponent``` prop to provide custom input and then we can remove value by updating state, but I wanna use DatePicker just like so without any custom input provided to it. there should be a way to clear input value from default input component.
I also tried using a ```ref``` to control the default input value but looks like you haven't used ```forwardRef``` when exporting component so that won't work either! so I have to query dom and update value manually.😑😕

**Comment by A-Kasaaian** [comment]
@masarbazi  Please take a look at [controlValue](https://github.com/A-Kasaaian/react-advance-jalaali-datepicker/blob/master/examples/controlValue.js) example linked in README.md. Ignore the custom input, you can simply pass controlVslue and preSelected props to set the value.

**Comment by masarbazi** [comment]
thx.
