### ISSUE TITLE
Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by sadegh-khan** [A-Kasaaian/react-advance-jalaali-datepicker#45]
hi,
when i run "npm i" command on my machine, i get bellow error:

verbose stack Error: /var/www/----------/node_modules/react-advance-jalaali-datepicker: 

the full log is:

62 verbose stack Error: /var/www/--------/node_modules/react-advance-jalaali-datepicker: Appears to be a git repo or submodule.
62 verbose stack     at /usr/share/npm/node_modules/npm-install-checks/index.js:138:15
62 verbose stack     at callback (/usr/share/nodejs/graceful-fs/polyfills.js:295:20)
62 verbose stack     at FSReqWrap.oncomplete (fs.js:154:5)
63 verbose cwd /var/www/--------
64 verbose Linux 5.4.0-90-generic
65 verbose argv "/usr/bin/node" "/usr/bin/npm" "audit" "fix"
66 verbose node v10.19.0
67 verbose npm  v6.14.4
68 error code EISGIT
69 error path /var/www/--------/node_modules/react-advance-jalaali-datepicker
70 error git /var/www/--------/node_modules/react-advance-jalaali-datepicker: Appears to be a git repo or submodule.
71 error git /var/www/--------/node_modules/react-advance-jalaali-datepicker
72 error git Refusing to remove it. Update manually,
72 error git or move it out of the way first.
73 verbose exit [ 1, true ]

 - OS: [Ubuntu 20.04.3]
 - react : [17.0.2]
 - Node : [v10.19.0]
 - npm : [6.14.4]

**Comment by A-Kasaaian** [comment]
It never happened before. Try `rm -rf node_modules/*/.git/` then install it.

**Comment by A-Kasaaian** [comment]
No reply for a long time
