### ISSUE TITLE
Set Custom Style to calendar

### ISSUE THREAD

**Issue by shg1998** [A-Kasaaian/react-advance-jalaali-datepicker#46]
Hi,
can we Customize Style of calendar manually?
and how?

**Comment by A-Kasaaian** [comment]
You can pass custom input as a prop. You also have the option to add `containerClass` to input container and style it. Then, there is another prop `customClass` that gives you the option to pass class name to the datepicker container and override any style within that. For that purpose, You should use nested style and override some existing styles or add new properties.

Unfortunately, there is  currently no theme option.

**Comment by A-Kasaaian** [comment]
If you need the theme option, please create a new issue and label it as request. Thanks.
