### ISSUE TITLE
Cannot read properties of undefined (reading 'value') when selecting hour

### ISSUE THREAD

**Issue by nima-sayadi** [A-Kasaaian/react-advance-jalaali-datepicker#51]
When using date time picker, As I want to choose time ( only hour ) , I receive an error stating that it Cannot read properties of undefined (reading 'value').

Error origin : node_modules\react-advance-jalaali-datepicker\dist\Partials\TimePicker.js (124:0)

1. add date time picker to your page.
2. Click on time.
3. Select hour section.
4. choose an hour.
5. See error.

 - OS: Windows 10
 - Browser: Chrome latest version
 - React Version 18.2.0

**Comment by A-Kasaaian** [comment]
Sorry for late reply, I didn't get any email for this issue.

Please, double check with the documentation. If the problem still exist, reply with your render method. I'd ask you have done any tricky change to remove minutes input.

**Comment by mostafahosseinidb** [comment]
i have this problem too.

how can i resolve this?

**Comment by A-Kasaaian** [comment]
Hi, I'm just back from xmas holiday. I have not faced the issue. I'm taking a deeper look today.
