### ISSUE TITLE
Request for Enhancement: Close Calendar When Clicked Outside Input

### ISSUE THREAD

**Issue by elhamest** [A-Kasaaian/react-advance-jalaali-datepicker#53]
hi,
I hope this message finds you well. I wanted to bring to your attention an enhancement request. 
Currently, when a user clicks on the input of datalist and the calendar opens, there is no built-in functionality to close the calendar when the user clicks outside of the input.
I believe it would greatly improve the user experience if the calendar automatically closes when the user interacts outside of the input area.

**Comment by A-Kasaaian** [comment]
It's simply achievable with custom input. You can add an input and implement an outside click for it. I understand your suggestion here, but the purposed behaviour is such that implementing it in the library may affect current users.

**Comment by elhamest** [comment]
hi,
thank you for your response.
