### ISSUE TITLE
update the deprecated core-js

### ISSUE THREAD

**Issue by alimodev** [A-Kasaaian/react-advance-jalaali-datepicker#58]
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

npm ls core-js
`-- react-advance-jalaali-datepicker@1.5.1
  `-- @babel/runtime-corejs2@7.23.8
    `-- core-js@2.6.12

**Comment by A-Kasaaian** [comment]
I have recently updated babel. I wasn't expecting it. I resolve it in next release. I do my best to do it tonight. Thanks for reportin
