### ISSUE TITLE
Unclickable days in current month until choosing another month.

### ISSUE THREAD

**Issue by arman-ebrahimi** [A-Kasaaian/react-advance-jalaali-datepicker#59]
My datepicker was working well, but today when I open datepicker, the days in current month are invisible and unclickable, and they are visible just when I choose another month and come back to current month.

![Screenshot (92)](https://github.com/A-Kasaaian/react-advance-jalaali-datepicker/assets/71581781/51108868-0c10-4bab-9342-6a03477ff56e)

**Comment by A-Kasaaian** [comment]
Yes, I could reproduce it. I'm gonna fix it and publish a hot fix for it today.

**Comment by A-Kasaaian** [comment]
I've published version 1.5.2 as a hotfix for this issue. Please install the latest version.
