### ISSUE TITLE
Can't choose hour 00 AND can't choose minute 00

### ISSUE THREAD

**Issue by hesamfarhang** [A-Kasaaian/react-advance-jalaali-datepicker#6]
in DateTimePicker when we choose minute or hour 00, the DateTimePicker showes error "دقیقه حداکثر ۶۰ باشد" 
react-advance-jalaali-datepicker/src/Partials/TimePicker.js
react-advance-jalaali-datepicker/dist/Partials/TimePicker.js
```
if( houraInt > 0 && houraInt < 24){
                if( minuteInt > 0 && minuteInt < 60){
```
should be
```
if( houraInt >= 0 && houraInt < 24){
                if( minuteInt >= 0 && minuteInt < 60){
```

**Comment by A-Kasaaian** [comment]
Thx, Further tests are required before merging your commit. If you want to test, you should test date-time range picker where you select  00:XX or XX:00 for start time. I'll test asap

**Comment by A-Kasaaian** [comment]
New version is released and it's fixed now.
